version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    command: node dist/main.js

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
