version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    command: node dist/main.js

  nginx:
    image: jonasal/nginx-certbot:3
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTBOT_EMAIL=vigor01695@email.com
    volumes:
      - ./nginx_secrets:/etc/letsencrypt                  # 憑證持久化
      - ./user_conf.d:/etc/nginx/user_conf.d:ro           # 掛載用戶配置到 user_conf.d
    restart: always
    depends_on:
      - app
