name: Deploy to EC2

on:
  push:
    branches:
      - dev  # 監聽 main 分支變動

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH to EC2 and deploy
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ec2-user
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST << 'EOF'
            cd /home/ec2-user/Parking-Assistant-Backend
            git checkout dev
            git pull
            docker-compose up --build -d
            docker system prune -f
          EOF
